apiVersion: v1
kind: PersistentVolume
metadata:
  name: mnist-model-serve-uuidgen
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mms
  hostPath:
    path: /cephfs/model-traning/uuidgen

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mnist-model-serve-uuidgen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mms

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-inception-mnist-uuidgen-get
      prefix: /models/inception-mnist-uuidgen/
      rewrite: /
      method: GET
      service: inception-mnist-uuidgen.kubeflow:8000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-mapping-inception-mnist-uuidgen-post
      prefix: /models/inception-mnist-uuidgen/
      rewrite: /model/inception-mnist-uuidgen:predict
      method: POST
      service: inception-mnist-uuidgen.kubeflow:8000
  labels:
    app: inception-mnist-uuidgen
    app.kubernetes.io/deploy-manager: ksonnet
  name: inception-mnist-uuidgen
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: http-tf-serving-proxy
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: inception-mnist-uuidgen
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inception-mnist-uuidgen
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: inception-mnist-uuidgen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inception-mnist-uuidgen
    spec:
      containers:
      - args:
        - /usr/bin/tensorflow_model_server
        - --port=9000
        - --model_name=inception-mnist-uuidgen
        - --model_base_path=/home
        image: registry.cn-shenzhen.aliyuncs.com/gcr_io_kubeflow/tf-model-server-cpu:v20180327-995786ec
        imagePullPolicy: IfNotPresent
        name: inception-mnist-uuidgen
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - name: inception-persisten-storage
          mountPath: /home/
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: inception-persisten-storage
        persistentVolumeClaim:
          claimName: mnist-model-serve-uuidgen