apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-traning-pv-uuidgen
  labels:
    tfdata: mt-uuidgen
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /cephfs/model-traning/uuidgen

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-traning-pv-claim-uuidgen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      tfdata: mt-uuidgen

---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-traning-uuidgen
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model-traning
        tb-job: model-traning
      name: model-traning
      namespace: default
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/gcr_io_kubeflow/kubeflow-train:1533699520
        imagePullPolicy: IfNotPresent
        name: model-traning
        resources: {}
        volumeMounts:
        - name: model-traning-persisten-storage
          mountPath: /home/tensorflow/model
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: model-traning-persisten-storage
        persistentVolumeClaim:
          claimName: model-traning-pv-claim-uuidgen