apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-traning-pv-uuidgen
  labels:
    tfdata: mt-uuidgen
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /cephfs/model-traning/uuidgen

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-traning-pv-claim-uuidgen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      tfdata: mt-uuidgen

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: model-traning-uuidgen
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: model-traning
      tb-job: model-traning
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model-traning
        tb-job: model-traning
      name: model-traning
      namespace: default
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/gcr_io_kubeflow/kubeflow-train:1533699520
        imagePullPolicy: IfNotPresent
        name: model-traning
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: model-traning-persisten-storage
          mountPath: /home/tensorflow/model
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: model-traning-persisten-storage
        persistentVolumeClaim:
          claimName: model-traning-pv-claim-uuidgen