apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-hub-lb-katacoda
  name: tf-hub-lb-katacoda
spec:
  type: NodePort
  ports:
  - name: hub
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: tf-hub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: centraldashboard-katacoda
  name: centraldashboard-katacoda
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
  selector:
    app: centraldashboard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador-katacoda
spec:
  type: NodePort
  ports:
  - name: ambassador
    port: 30080
    protocol: TCP
  selector:
    service: ambassador