apiVersion: v1
kind: PersistentVolume
metadata:
  name: tensorboard-pv-uuidgen
  labels:
    tfdata: tb-uuidgen
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /cephfs/jupyterhubpv/uuidgen

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorboard-pv-claim-uuidgen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      tfdata: tb-uuidgen

---
apiVersion: v1
kind: Service
metadata:
  name: tensorboard-manual-uuidgen
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: tensorboard
    tb-job: tensorboard
  sessionAffinity: None
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorboard-manual-uuidgen
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tensorboard
      tb-job: tensorboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tensorboard
        tb-job: tensorboard
      name: tensorboard
      namespace: default
    spec:
      containers:
      - command:
        - /usr/local/bin/tensorboard
        - --logdir=/notebooks/tensorflow/logs
        - --port=80
        image: tensorflow/tensorflow:1.8.0
        imagePullPolicy: IfNotPresent
        name: tensorboard
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: tensorbord-persisten-storage
          mountPath: /notebooks/tensorflow/logs
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tensorbord-persisten-storage
        persistentVolumeClaim:
          claimName: tensorboard-pv-claim-uuidgen